# Generated by Django 4.0.3 on 2022-04-04 06:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentMake', models.CharField(max_length=100, null=True)),
                ('AppointmentModel', models.CharField(max_length=100, null=True)),
                ('AppointmentYear', models.CharField(max_length=4, null=True)),
                ('AppointmentVIN', models.CharField(max_length=30, null=True)),
                ('AppointmentEmail', models.EmailField(max_length=254, null=True)),
                ('AppointmentServices', djongo.models.fields.JSONField(null=True)),
                ('AppointmentDate', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
